# Generated by Django 2.0.7 on 2019-07-12 16:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='version',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)]),
        ),
    ]
