# Generated by Django 2.0.7 on 2019-07-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='url',
            field=models.URLField(),
        ),
    ]
